### ISSUE TITLE
Integration not working in HA 2021.8.8

### ISSUE THREAD

**Issue by irekzielinski** [robmarkcole/HASS-Google-Vision#10]
Hi. Thanks for the excellent integration.
I noticed it faling in latest version of HA. 
Dependency error?
Any idea how to fix it?
Thanks!

`
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/google_vision/image_processing.py:17
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:47:59 (1 occurrences)
Last logged: 18:47:59

[139827431124704] (google-auth 2.0.0 (/usr/local/lib/python3.9/site-packages), Requirement.parse('google-auth<2.0dev,>=1.25.0'), {'google-api-core'})
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 728, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 148, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 923, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 212, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/google_vision/image_processing.py", line 17, in <module>
    import gvision.core as gv
  File "/usr/local/lib/python3.9/site-packages/gvision/core.py", line 6, in <module>
    from google.cloud import vision
  File "/usr/local/lib/python3.9/site-packages/google/cloud/vision.py", line 17, in <module>
    from google.cloud.vision_v1 import ImageAnnotatorClient
  File "/usr/local/lib/python3.9/site-packages/google/cloud/vision_v1/__init__.py", line 25, in <module>
    from google.cloud.vision_v1.gapic import image_annotator_client as iac
  File "/usr/local/lib/python3.9/site-packages/google/cloud/vision_v1/gapic/image_annotator_client.py", line 41, in <module>
    _GAPIC_LIBRARY_VERSION = pkg_resources.get_distribution("google-cloud-vision").version
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 466, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 342, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (google-auth 2.0.0 (/usr/local/lib/python3.9/site-packages), Requirement.parse('google-auth<2.0dev,>=1.25.0'), {'google-api-core'})

`

**Comment by irekzielinski** [comment]
a work around is to issue those commands in HA console:
pip uninstall google-auth
pip install google-auth

HA docker package I have been using has an old version of google-auth
I think this is more of HA issue than of this component, so closing the issue here
