### ISSUE TITLE
Setup error in ha 0.111

### ISSUE THREAD

**Issue by brucewinter** [robmarkcole/HASS-Google-Vision#8]
Rob,

Thanks for creating this integration!  I've been using it for a few months with no issue.   

However ... then new HA 0.111 release seems to have broken it, errata below.   Reverting aback to 0.110.4 fixes the problem.  Any suggestions?

Bruce Winter

------

2020-06-21 15:16:09 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration image_processing - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 55, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 151, in _async_setup_component
    hass, config, integration
  File "/usr/src/homeassistant/homeassistant/config.py", line 780, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 273, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/google_vision/image_processing.py", line 17, in <module>
    import gvision.core as gv
  File "/usr/local/lib/python3.7/site-packages/gvision/core.py", line 6, in <module>
    from google.cloud import vision
  File "/usr/local/lib/python3.7/site-packages/google/cloud/vision.py", line 17, in <module>
    from google.cloud.vision_v1 import ImageAnnotatorClient
  File "/usr/local/lib/python3.7/site-packages/google/cloud/vision_v1/__init__.py", line 20, in <module>
    from google.cloud.vision_helpers.decorators import add_single_feature_methods
  File "/usr/local/lib/python3.7/site-packages/google/cloud/vision_helpers/__init__.py", line 18, in <module>
    from google.api_core import protobuf_helpers as protobuf
  File "/usr/local/lib/python3.7/site-packages/google/api_core/protobuf_helpers.py", line 21, in <module>
    from google.protobuf import field_mask_pb2
  File "/usr/local/lib/python3.7/site-packages/google/protobuf/field_mask_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by robmarkcole** [comment]
@brucewinter is this still an issue?

**Comment by brucewinter** [comment]
Sorry, I forgot about this issue.   It seems no longer a problem, but I also forgot how/when it got fixed.   

Thanks again for the integration!
